from .admin import AdminApplicationUpdate, AdminDecision, PaymentMark, ProjectReview, TaskCreate, TaskUpdate
from .ai import (
    AIAskRequest,
    AIAskResponse,
    AIProjectReviewRequest,
    CodeAnalysisRequest,
    DomainRecommendationRequest,
    InterviewQuestionRequest,
    InterviewSubmitRequest,
    ResumeAnalysisRequest,
    RoadmapRequest,
)
from .documents import DocumentGenerateRequest, DocumentRevokeRequest
from .enterprise import (
    CandidatePipelineUpdate,
    CommunityCommentCreate,
    CommunityPostCreate,
    EmailLogCreate,
    HackathonCreate,
    HackathonSubmit,
    RecruiterContactRequest,
    RecruiterShortlistRequest,
    RoleManagementRequest,
    TeamCreate,
    TeamMemberAdd,
    TeamUpdate,
)
from .freelance import FreelanceProjectCreate
from .lms import (
    AssignmentCreate,
    AssignmentReview,
    AssignmentSubmit,
    AttendanceMark,
    LearningMaterialCreate,
    MaterialProgressUpdate,
    QuizAttempt,
    QuizCreate,
)
from .placement import (
    AdminResumeReview,
    JobAlertCreate,
    LinkedInChecklistAdvancedUpdate,
    PlacementStatusUpdate,
    ResumeProfileUpdate,
)
from .projects import ProjectCreate, ProjectReviewRequest, ProjectSubmissionCreate
from .student import (
    ApplicationRequest,
    ChecklistUpdate,
    FinalProjectUpdate,
    LoginRequest,
    OtpResendRequest,
    OtpVerifyRequest,
    RegisterRequest,
)
from .support import SupportTicketCreate, SupportTicketMessageCreate, SupportTicketUpdate

__all__ = [
    "AdminApplicationUpdate",
    "AdminDecision",
    "AdminResumeReview",
    "AIAskRequest",
    "AIAskResponse",
    "AIProjectReviewRequest",
    "ApplicationRequest",
    "AssignmentCreate",
    "AssignmentReview",
    "AssignmentSubmit",
    "AttendanceMark",
    "ChecklistUpdate",
    "CodeAnalysisRequest",
    "CandidatePipelineUpdate",
    "CommunityCommentCreate",
    "CommunityPostCreate",
    "DocumentGenerateRequest",
    "DocumentRevokeRequest",
    "DomainRecommendationRequest",
    "EmailLogCreate",
    "FinalProjectUpdate",
    "FreelanceProjectCreate",
    "HackathonCreate",
    "HackathonSubmit",
    "InterviewQuestionRequest",
    "InterviewSubmitRequest",
    "JobAlertCreate",
    "LearningMaterialCreate",
    "LinkedInChecklistAdvancedUpdate",
    "LoginRequest",
    "MaterialProgressUpdate",
    "OtpResendRequest",
    "OtpVerifyRequest",
    "PaymentMark",
    "PlacementStatusUpdate",
    "ProjectReview",
    "ProjectCreate",
    "ProjectReviewRequest",
    "ProjectSubmissionCreate",
    "QuizAttempt",
    "QuizCreate",
    "RegisterRequest",
    "RecruiterContactRequest",
    "RecruiterShortlistRequest",
    "ResumeAnalysisRequest",
    "ResumeProfileUpdate",
    "RoleManagementRequest",
    "RoadmapRequest",
    "SupportTicketCreate",
    "SupportTicketMessageCreate",
    "SupportTicketUpdate",
    "TaskCreate",
    "TeamCreate",
    "TeamMemberAdd",
    "TeamUpdate",
    "TaskUpdate",
]
